spring:
  application:
    name: security-analysis-server

  cloud:
    function:
      definition: consumeRun;consumeCancel
    stream:
      bindings:
        consumeRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.run
          group: saGroup
        publishRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.run
        publishResult-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.result
        consumeCancel-in-0:
            destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.cancel
        publishCancel-out-0:
            destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.cancel
        publishStopped-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.stopped
      source: publishRun;publishResult;publishCancel;publishStopped

  jpa:
    properties:
      hibernates:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100

logging:
  level:
    ROOT: INFO

dbName: sa
