spring:
  application:
    name: security-analysis-server

  cloud:
    function:
      definition: consumeRun;consumeCancel
    stream:
      bindings:
        consumeRun-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.run
          group: saGroup
          consumer:
            concurrency: 2
        publishRun-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.run
        publishResult-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.result
        consumeCancel-in-0:
            destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.cancel
        publishCancel-out-0:
            destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.cancel
        publishStopped-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.stopped
        publishFailed-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}sa.failed
      source: publishRun;publishResult;publishCancel;publishStopped;publishFailed

powsybl-ws:
  database:
    name: sa

# default values for loadflow providers "Hades2" or "OpenLoadFlow"
loadflow:
  default-provider: OpenLoadFlow
