spring:
  rabbitmq:
    addresses: localhost
    port: 5672

  cloud:
    function:
      definition: consumeRun;publishRun;publishResult
    stream:
      bindings:
        consumeRun-in-0:
          destination: sa.run
          group: saGroup
        publishRun-out-0:
          destination: sa.run
        publishResult-out-0:
          destination: sa.result

server:
  port: 5023

network-store-server:
  base-uri: http://localhost:8080

actions-server:
  base-uri: http://localhost:5021

securityAnalysisFactoryClass: com.rte_france.powsybl.hades2.Hades2SecurityAnalysisFactory

logging:
  level:
    ROOT: INFO
