spring:
  profiles:
    active: default,local

  rabbitmq:
    addresses: rabbitmq
    port: 5672

  cloud:
    function:
      definition: consumeRun;consumeCancel
    stream:
      bindings:
        consumeRun-in-0:
          destination: sa.run
          group: saGroup
        publishRun-out-0:
          destination: sa.run
        publishResult-out-0:
          destination: sa.result
        consumeCancel-in-0:
            destination: sa.cancel
        publishCancel-out-0:
            destination: sa.cancel
        publishStopped-out-0:
          destination: sa.stopped
      source: publishRun;publishResult;publishCancel;publishStopped

server:
  forward-headers-strategy: framework

logging:
  level:
    ROOT: INFO
