server:
  port: 5023

spring:
  rabbitmq:
    addresses: localhost

network-store-server:
  base-uri: http://localhost:8080

actions-server:
  base-uri: http://localhost:5022

# default values for loadflow providers "Hades2" or "OpenSecurityAnalysis"
loadflow:
  default-provider: OpenSecurityAnalysis