server:
  port: 5023

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
   host: localhost



backing-services:
  actions-server:
    base-uri: http://localhost:5022
  report-server:
    base-uri: http://localhost:5028
  network-store-server:
    base-uri: http://localhost:8080
